In [6]:
import numpy as np
#交换矩阵的其中两行
a = np.arange(25).reshape(5,5)
print a
a[[0,1]] = a[[1,0]]
print a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [7]:
#找出数组中与给定值最接近的数
z = np.array([[0,1,2,3],[4,5,6,7]])
a = 5.1
print np.abs(z-a).argmin()

5


In [18]:
#判断二维矩阵中有没有一整列数为0？
import numpy as np
z = np.random.randint(0,3,(2,10))
print (z)
print (z.all(axis=0))
print (z.any(axis=0))
#help(np.any)

[[1 2 1 1 0 2 0 0 0 2]
 [2 1 1 2 0 2 1 0 2 2]]
[ True  True  True  True False  True False False False  True]
[ True  True  True  True False  True  True False  True  True]


In [11]:
#生成二维的高斯矩阵
#help(np.random.randint)

In [10]:
x,y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
#print (x)
#print (y)
D = np.sqrt(x**2+y**2)
#print D
sigma,mu = 1,0
a = np.exp(-(D-mu)**2/(2*sigma**2))
print (a)
#help(np.meshgrid)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0